# Generated by Django 3.1.7 on 2021-07-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='health',
            new_name='good',
        ),
        migrations.RemoveField(
            model_name='note',
            name='power',
        ),
    ]
